{% set name = "scikit-llm" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit_llm-{{ version }}.tar.gz
  sha256: 4134e8bc2e7e12ec8000fe832af3b168734dadd66f65b5b72599aa91a063f243

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - python
    - wheel
    - setuptools >=61.0
    - pip
  run:
    - python
    - scikit-learn >=1.1.0,<2.0.0
    - pandas >=1.5.0,<3.0.0
    - openai >=1.2.0,<2.0.0
    - tqdm >=4.60.0,<5.0.0
    - google-cloud-aiplatform >=1.27.0,<2.0.0
  run_constrained:
    - llama-cpp-python >=0.2.82,<0.2.83
    - annoy>=1.17.2,<2.0.0

test:
  source_files:
    - tests
  imports:
    - skllm
    - skllm.datasets
    - skllm.llm
    - skllm.llm.gpt
    - skllm.llm.vertex
    - skllm.memory
    - skllm.models
    - skllm.models._base
    - skllm.models.gpt
    - skllm.models.vertex
    - skllm.prompts
    - skllm.utils
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://beastbyte.ai/scikit-llm.html
  summary: 'Scikit-LLM: Seamlessly integrate powerful language models like ChatGPT into scikit-learn for enhanced text analysis tasks.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Scikit-LLM is a Python library designed to streamline the development of complex
    and production-ready NLP pipelines. It achieves this by offering a conventional
    scikit-learn API, thus abstracting the complexity of working with different large
    language models (LLMs).

    Scikit-LLM can interact with a variety of LLM providers, whether they are running
    locally (such as GPT4All) or in the cloud (including Azure, OpenAI, and Vertex AI).

    The library supports a wide range of text analysis tasks, including text classification
    and text-to-text modeling. For complex scenarios, multiple tasks can be chained
    together to form a scikit-learn pipeline.

    Additionally, Scikit-LLM supports various prompting strategies (such as zero-shot,
    few-shot, and dynamic few-shot) and tuning options, which can significantly
    enhance model performance on a specific task.
  doc_url: https://skllm.beastbyte.ai/
  dev_url: https://github.com/BeastByteAI/scikit-llm

extra:
  recipe-maintainers:
    - snegireff
